-- MySQL Script generated by MySQL Workbench
-- Mon Jan  9 04:38:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gangodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gangodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gangodb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `gangodb` ;

-- -----------------------------------------------------
-- Table `gangodb`.`academic_rank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gangodb`.`academic_rank` (
  `academic_rank_id` VARCHAR(45) NOT NULL,
  `academic_rank_title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`academic_rank_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gangodb`.`degree_level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gangodb`.`degree_level` (
  `degree_level_id` INT NOT NULL,
  `degree_level_title` VARCHAR(45) NOT NULL,
  `course_course_id` VARCHAR(20) NOT NULL,
  `course_degree_level_degree_level_id` INT NOT NULL,
  PRIMARY KEY (`degree_level_id`, `course_course_id`, `course_degree_level_degree_level_id`),
  INDEX `fk_degree_level_course1_idx` (`course_course_id` ASC, `course_degree_level_degree_level_id` ASC) VISIBLE,
  CONSTRAINT `fk_degree_level_course1`
    FOREIGN KEY (`course_course_id` , `course_degree_level_degree_level_id`)
    REFERENCES `gangodb`.`course` (`course_id` , `degree_level_degree_level_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gangodb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gangodb`.`course` (
  `course_id` VARCHAR(20) NOT NULL,
  `course_name` VARCHAR(255) NOT NULL,
  `degree_level_degree_level_id` INT NOT NULL,
  PRIMARY KEY (`course_id`, `degree_level_degree_level_id`),
  INDEX `fk_course_degree_level1_idx` (`degree_level_degree_level_id` ASC) VISIBLE,
  CONSTRAINT `fk_course_degree_level1`
    FOREIGN KEY (`degree_level_degree_level_id`)
    REFERENCES `gangodb`.`degree_level` (`degree_level_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gangodb`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gangodb`.`students` (
  `student_id` INT NOT NULL,
  `student_name` VARCHAR(255) NOT NULL,
  `student_surname` VARCHAR(255) NOT NULL,
  `student_age` INT NOT NULL,
  `course_course_id` VARCHAR(20) NOT NULL,
  `course_degree_level_degree_level_id` INT NOT NULL,
  PRIMARY KEY (`student_id`, `course_course_id`, `course_degree_level_degree_level_id`),
  INDEX `fk_students_course1_idx` (`course_course_id` ASC, `course_degree_level_degree_level_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_course1`
    FOREIGN KEY (`course_course_id` , `course_degree_level_degree_level_id`)
    REFERENCES `gangodb`.`course` (`course_id` , `degree_level_degree_level_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gangodb`.`module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gangodb`.`module` (
  `module_id` VARCHAR(20) NOT NULL,
  `module_title` VARCHAR(255) NOT NULL,
  `course_course_id` VARCHAR(20) NOT NULL,
  `course_degree_level_degree_level_id` INT NOT NULL,
  PRIMARY KEY (`module_id`, `course_course_id`, `course_degree_level_degree_level_id`),
  INDEX `fk_module_course1_idx` (`course_course_id` ASC, `course_degree_level_degree_level_id` ASC) VISIBLE,
  CONSTRAINT `fk_module_course1`
    FOREIGN KEY (`course_course_id` , `course_degree_level_degree_level_id`)
    REFERENCES `gangodb`.`course` (`course_id` , `degree_level_degree_level_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gangodb`.`meeting_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gangodb`.`meeting_room` (
  `meeting_room_id` INT NOT NULL,
  `meeting_room_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`meeting_room_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gangodb`.`lecturers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gangodb`.`lecturers` (
  `lecturers_id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `academic_rank_academic_rank_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`lecturers_id`, `academic_rank_academic_rank_id`),
  INDEX `fk_lecturers_academic_rank_idx` (`academic_rank_academic_rank_id` ASC) VISIBLE,
  CONSTRAINT `fk_lecturers_academic_rank`
    FOREIGN KEY (`academic_rank_academic_rank_id`)
    REFERENCES `gangodb`.`academic_rank` (`academic_rank_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gangodb`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gangodb`.`session` (
  `session_id` INT NOT NULL,
  `session_date` DATE NOT NULL,
  `session_time` DATETIME NOT NULL,
  `module_module_id` VARCHAR(20) NOT NULL,
  `module_course_course_id` VARCHAR(20) NOT NULL,
  `module_course_degree_level_degree_level_id` INT NOT NULL,
  `meeting_room_meeting_room_id` INT NOT NULL,
  `lecturers_lecturers_id` INT NOT NULL,
  `lecturers_academic_rank_academic_rank_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`session_id`, `module_module_id`, `module_course_course_id`, `module_course_degree_level_degree_level_id`, `meeting_room_meeting_room_id`, `lecturers_lecturers_id`, `lecturers_academic_rank_academic_rank_id`),
  INDEX `fk_session_module1_idx` (`module_module_id` ASC, `module_course_course_id` ASC, `module_course_degree_level_degree_level_id` ASC) VISIBLE,
  INDEX `fk_session_meeting_room1_idx` (`meeting_room_meeting_room_id` ASC) VISIBLE,
  INDEX `fk_session_lecturers1_idx` (`lecturers_lecturers_id` ASC, `lecturers_academic_rank_academic_rank_id` ASC) VISIBLE,
  CONSTRAINT `fk_session_module1`
    FOREIGN KEY (`module_module_id` , `module_course_course_id` , `module_course_degree_level_degree_level_id`)
    REFERENCES `gangodb`.`module` (`module_id` , `course_course_id` , `course_degree_level_degree_level_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_session_meeting_room1`
    FOREIGN KEY (`meeting_room_meeting_room_id`)
    REFERENCES `gangodb`.`meeting_room` (`meeting_room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_session_lecturers1`
    FOREIGN KEY (`lecturers_lecturers_id` , `lecturers_academic_rank_academic_rank_id`)
    REFERENCES `gangodb`.`lecturers` (`lecturers_id` , `academic_rank_academic_rank_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gangodb`.`attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gangodb`.`attendance` (
  `student_id` VARCHAR(45) NOT NULL,
  `session_id` INT NOT NULL,
  `attendance_rec` BIT(1) NOT NULL,
  PRIMARY KEY (`student_id`, `session_id`),
  CONSTRAINT `student_id`
    FOREIGN KEY (`student_id` , `session_id`)
    REFERENCES `gangodb`.`students` (`student_id` , `course_course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `session_id`
    FOREIGN KEY (`student_id` , `session_id`)
    REFERENCES `gangodb`.`session` (`session_id` , `session_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gangodb`.`campus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gangodb`.`campus` (
  `campus_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`campus_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gangodb`.`school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gangodb`.`school` (
  `school_id` VARCHAR(20) NOT NULL,
  `school_name` VARCHAR(255) NOT NULL,
  `campus_campus_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`school_id`, `campus_campus_id`),
  INDEX `fk_school_campus1_idx` (`campus_campus_id` ASC) VISIBLE,
  CONSTRAINT `fk_school_campus1`
    FOREIGN KEY (`campus_campus_id`)
    REFERENCES `gangodb`.`campus` (`campus_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gangodb`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gangodb`.`department` (
  `department_id` VARCHAR(45) NOT NULL,
  `department_title` VARCHAR(255) NOT NULL,
  `school_school_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`department_id`, `school_school_id`),
  INDEX `fk_department_school1_idx` (`school_school_id` ASC) VISIBLE,
  CONSTRAINT `fk_department_school1`
    FOREIGN KEY (`school_school_id`)
    REFERENCES `gangodb`.`school` (`school_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gangodb`.`semester`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gangodb`.`semester` (
  `semester_id` VARCHAR(20) NOT NULL,
  `semester_year` INT NOT NULL,
  `semester_code` INT NULL DEFAULT NULL,
  `course_course_id` VARCHAR(20) NOT NULL,
  `course_degree_level_degree_level_id` INT NOT NULL,
  `module_module_id` VARCHAR(20) NOT NULL,
  `module_course_course_id` VARCHAR(20) NOT NULL,
  `module_course_degree_level_degree_level_id` INT NOT NULL,
  PRIMARY KEY (`semester_id`, `course_course_id`, `course_degree_level_degree_level_id`, `module_module_id`, `module_course_course_id`, `module_course_degree_level_degree_level_id`),
  INDEX `fk_semester_course1_idx` (`course_course_id` ASC, `course_degree_level_degree_level_id` ASC) VISIBLE,
  INDEX `fk_semester_module1_idx` (`module_module_id` ASC, `module_course_course_id` ASC, `module_course_degree_level_degree_level_id` ASC) VISIBLE,
  CONSTRAINT `fk_semester_course1`
    FOREIGN KEY (`course_course_id` , `course_degree_level_degree_level_id`)
    REFERENCES `gangodb`.`course` (`course_id` , `degree_level_degree_level_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_semester_module1`
    FOREIGN KEY (`module_module_id` , `module_course_course_id` , `module_course_degree_level_degree_level_id`)
    REFERENCES `gangodb`.`module` (`module_id` , `course_course_id` , `course_degree_level_degree_level_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
